### ISSUE TITLE
numpy.core._internal.AxisError in test_video.py

### ISSUE THREAD

**Issue by Cying212Jack** [SaoYan/bgsCNN#2]
If the frame picture in the video is gray, then the variable "frame" is 2 dimension-arrary in the first part.
This will cause an error when we want to combine two 2-d array in the second part as follow:
numpy.core._internal.AxisError: axis 2 is out of bounds for array of dimension 2.
- first part
`check = (frame[:,:,0] == frame[:,:,1])`
`if check.all():`    `frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)`

- second part
`input_data = np.concatenate([frame, bg_model], 2)`

**Comment by SaoYan** [comment]
In my case, gray-scale image is a 2-dim array (H-by-W-by-1).

But if it is not your case, feel free to adjust the code to your own need.

**Comment by SaoYan** [comment]
Thanks for your suggestion!

Numpy provides useful functions to expand or reduce dimensions of an array:
np.squeeze()
np.expand_dims()

Free free to modify the code and pull requests!
Thanks again!
