### ISSUE TITLE
What is the speed of bgsCNN

### ISSUE THREAD

**Issue by lzhaozi** [SaoYan/bgsCNN#5]
Hi,

Thanks for your great work. I am concerned about the bgs speed. For 720p video, how many fps can this algorithm reach? Can it surpass realtime speed?
Thanks again for your great work.

Yours,
Jeff

**Comment by SaoYan** [comment]
The speed relies much on thehardware.

In fact this work is pretty primitive. Since SuBSENSE runs on CPU, it limits the speed a lot.
