### ISSUE TITLE
bgsCNN_v6.py

### ISSUE THREAD

**Issue by orthosiphon** [SaoYan/bgsCNN#8]
When I tried to run `train.py`, I got error an message as follows,

> File "train.py", line 8, in <module>
>     from bgsCNN_v6 import bgsCNN_v6

I guess that the `bgsCNN_v6.py` has not been uploaded since the last update for `train.py`?

Thank you :smile_cat:

**Comment by SaoYan** [comment]
my fault ~ already fix it
