### ISSUE TITLE
Can the project run on GPU?

### ISSUE THREAD

**Issue by Wisgon** [SaoYan/bgsCNN#9]
I use tensorflow-gpu to run the code, but it still very slow and the gpu-util is always 0, and the memory of my two GPUs both full.

**Comment by Wisgon** [comment]
@SaoYan

**Comment by SaoYan** [comment]
I ran the code on GPU.

It is true that this code is memory consuming. More improvements are encouraged.

**Comment by Wisgon** [comment]
OK, thank you for replying.
